[package]
name = "papyrus-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
papyrus-parser = { path = "../papyrus-parser" }
papyrus-renderer = { path = "../papyrus-renderer" }
